# Generated by Django 6.0 on 2025-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('momo', 'Mobile Money')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovementlog',
            name='payment_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmovementlog',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
