# Generated by Django 6.0 on 2025-12-18 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stockmovement_payment_method_stockmovement_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='app.branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch', to='app.userinfo'),
        ),
    ]
